// Code generated by MockGen. DO NOT EDIT.
// Source: i_wallet_service.go

// Package api is a generated GoMock package.
package api

import (
	context "context"
	models "ewallet-wallet/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIWalletService is a mock of IWalletService interface.
type MockIWalletService struct {
	ctrl     *gomock.Controller
	recorder *MockIWalletServiceMockRecorder
}

// MockIWalletServiceMockRecorder is the mock recorder for MockIWalletService.
type MockIWalletServiceMockRecorder struct {
	mock *MockIWalletService
}

// NewMockIWalletService creates a new mock instance.
func NewMockIWalletService(ctrl *gomock.Controller) *MockIWalletService {
	mock := &MockIWalletService{ctrl: ctrl}
	mock.recorder = &MockIWalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWalletService) EXPECT() *MockIWalletServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIWalletService) Create(ctx context.Context, wallet *models.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIWalletServiceMockRecorder) Create(ctx, wallet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWalletService)(nil).Create), ctx, wallet)
}

// CreateWalletLink mocks base method.
func (m *MockIWalletService) CreateWalletLink(ctx context.Context, clientSource string, req *models.WalletLink) (*models.WalletStructOTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWalletLink", ctx, clientSource, req)
	ret0, _ := ret[0].(*models.WalletStructOTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWalletLink indicates an expected call of CreateWalletLink.
func (mr *MockIWalletServiceMockRecorder) CreateWalletLink(ctx, clientSource, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWalletLink", reflect.TypeOf((*MockIWalletService)(nil).CreateWalletLink), ctx, clientSource, req)
}

// CreditBalance mocks base method.
func (m *MockIWalletService) CreditBalance(ctx context.Context, userID uint64, req models.TransactionRequest) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreditBalance", ctx, userID, req)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreditBalance indicates an expected call of CreditBalance.
func (mr *MockIWalletServiceMockRecorder) CreditBalance(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreditBalance", reflect.TypeOf((*MockIWalletService)(nil).CreditBalance), ctx, userID, req)
}

// DebitBalance mocks base method.
func (m *MockIWalletService) DebitBalance(ctx context.Context, userID uint64, req models.TransactionRequest) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebitBalance", ctx, userID, req)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DebitBalance indicates an expected call of DebitBalance.
func (mr *MockIWalletServiceMockRecorder) DebitBalance(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebitBalance", reflect.TypeOf((*MockIWalletService)(nil).DebitBalance), ctx, userID, req)
}

// ExGetBalance mocks base method.
func (m *MockIWalletService) ExGetBalance(ctx context.Context, walletID int) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExGetBalance", ctx, walletID)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExGetBalance indicates an expected call of ExGetBalance.
func (mr *MockIWalletServiceMockRecorder) ExGetBalance(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExGetBalance", reflect.TypeOf((*MockIWalletService)(nil).ExGetBalance), ctx, walletID)
}

// ExternalTransaction mocks base method.
func (m *MockIWalletService) ExternalTransaction(ctx context.Context, req models.ExternalTransactionRequest) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalTransaction", ctx, req)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalTransaction indicates an expected call of ExternalTransaction.
func (mr *MockIWalletServiceMockRecorder) ExternalTransaction(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalTransaction", reflect.TypeOf((*MockIWalletService)(nil).ExternalTransaction), ctx, req)
}

// GetBalance mocks base method.
func (m *MockIWalletService) GetBalance(ctx context.Context, userID uint64) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockIWalletServiceMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockIWalletService)(nil).GetBalance), ctx, userID)
}

// GetWalletHistory mocks base method.
func (m *MockIWalletService) GetWalletHistory(ctx context.Context, userID uint64, param models.WalletHistoryParam) ([]models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletHistory", ctx, userID, param)
	ret0, _ := ret[0].([]models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletHistory indicates an expected call of GetWalletHistory.
func (mr *MockIWalletServiceMockRecorder) GetWalletHistory(ctx, userID, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletHistory", reflect.TypeOf((*MockIWalletService)(nil).GetWalletHistory), ctx, userID, param)
}

// WalletLinkConfirmation mocks base method.
func (m *MockIWalletService) WalletLinkConfirmation(ctx context.Context, walletID int, clientSource, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletLinkConfirmation", ctx, walletID, clientSource, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// WalletLinkConfirmation indicates an expected call of WalletLinkConfirmation.
func (mr *MockIWalletServiceMockRecorder) WalletLinkConfirmation(ctx, walletID, clientSource, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletLinkConfirmation", reflect.TypeOf((*MockIWalletService)(nil).WalletLinkConfirmation), ctx, walletID, clientSource, otp)
}

// WalletUnlink mocks base method.
func (m *MockIWalletService) WalletUnlink(ctx context.Context, walletID int, clientSource string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletUnlink", ctx, walletID, clientSource)
	ret0, _ := ret[0].(error)
	return ret0
}

// WalletUnlink indicates an expected call of WalletUnlink.
func (mr *MockIWalletServiceMockRecorder) WalletUnlink(ctx, walletID, clientSource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletUnlink", reflect.TypeOf((*MockIWalletService)(nil).WalletUnlink), ctx, walletID, clientSource)
}
