// Code generated by MockGen. DO NOT EDIT.
// Source: IWallet.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	models "ewallet-wallet/internal/models"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIWalletRepo is a mock of IWalletRepo interface.
type MockIWalletRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIWalletRepoMockRecorder
}

// MockIWalletRepoMockRecorder is the mock recorder for MockIWalletRepo.
type MockIWalletRepoMockRecorder struct {
	mock *MockIWalletRepo
}

// NewMockIWalletRepo creates a new mock instance.
func NewMockIWalletRepo(ctrl *gomock.Controller) *MockIWalletRepo {
	mock := &MockIWalletRepo{ctrl: ctrl}
	mock.recorder = &MockIWalletRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWalletRepo) EXPECT() *MockIWalletRepoMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockIWalletRepo) CreateWallet(ctx context.Context, wallet *models.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockIWalletRepoMockRecorder) CreateWallet(ctx, wallet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockIWalletRepo)(nil).CreateWallet), ctx, wallet)
}

// CreateWalletTrx mocks base method.
func (m *MockIWalletRepo) CreateWalletTrx(ctx context.Context, walletHistory *models.WalletTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWalletTrx", ctx, walletHistory)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWalletTrx indicates an expected call of CreateWalletTrx.
func (mr *MockIWalletRepoMockRecorder) CreateWalletTrx(ctx, walletHistory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWalletTrx", reflect.TypeOf((*MockIWalletRepo)(nil).CreateWalletTrx), ctx, walletHistory)
}

// GetWalletByID mocks base method.
func (m *MockIWalletRepo) GetWalletByID(ctx context.Context, walletID int) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByID", ctx, walletID)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByID indicates an expected call of GetWalletByID.
func (mr *MockIWalletRepoMockRecorder) GetWalletByID(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByID", reflect.TypeOf((*MockIWalletRepo)(nil).GetWalletByID), ctx, walletID)
}

// GetWalletByUserID mocks base method.
func (m *MockIWalletRepo) GetWalletByUserID(ctx context.Context, userID uint64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByUserID", ctx, userID)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByUserID indicates an expected call of GetWalletByUserID.
func (mr *MockIWalletRepoMockRecorder) GetWalletByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByUserID", reflect.TypeOf((*MockIWalletRepo)(nil).GetWalletByUserID), ctx, userID)
}

// GetWalletHistory mocks base method.
func (m *MockIWalletRepo) GetWalletHistory(ctx context.Context, walletID, offset, limit int, transactionType string) ([]models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletHistory", ctx, walletID, offset, limit, transactionType)
	ret0, _ := ret[0].([]models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletHistory indicates an expected call of GetWalletHistory.
func (mr *MockIWalletRepoMockRecorder) GetWalletHistory(ctx, walletID, offset, limit, transactionType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletHistory", reflect.TypeOf((*MockIWalletRepo)(nil).GetWalletHistory), ctx, walletID, offset, limit, transactionType)
}

// GetWalletLink mocks base method.
func (m *MockIWalletRepo) GetWalletLink(ctx context.Context, walletID int, clientSource string) (models.WalletLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletLink", ctx, walletID, clientSource)
	ret0, _ := ret[0].(models.WalletLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletLink indicates an expected call of GetWalletLink.
func (mr *MockIWalletRepoMockRecorder) GetWalletLink(ctx, walletID, clientSource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletLink", reflect.TypeOf((*MockIWalletRepo)(nil).GetWalletLink), ctx, walletID, clientSource)
}

// GetWalletTransactionByReference mocks base method.
func (m *MockIWalletRepo) GetWalletTransactionByReference(ctx context.Context, reference string) (models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletTransactionByReference", ctx, reference)
	ret0, _ := ret[0].(models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletTransactionByReference indicates an expected call of GetWalletTransactionByReference.
func (mr *MockIWalletRepoMockRecorder) GetWalletTransactionByReference(ctx, reference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletTransactionByReference", reflect.TypeOf((*MockIWalletRepo)(nil).GetWalletTransactionByReference), ctx, reference)
}

// InsertWalletLink mocks base method.
func (m *MockIWalletRepo) InsertWalletLink(ctx context.Context, req *models.WalletLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWalletLink", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWalletLink indicates an expected call of InsertWalletLink.
func (mr *MockIWalletRepoMockRecorder) InsertWalletLink(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWalletLink", reflect.TypeOf((*MockIWalletRepo)(nil).InsertWalletLink), ctx, req)
}

// UpdateBalance mocks base method.
func (m *MockIWalletRepo) UpdateBalance(ctx context.Context, userID uint64, amount float64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, userID, amount)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockIWalletRepoMockRecorder) UpdateBalance(ctx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockIWalletRepo)(nil).UpdateBalance), ctx, userID, amount)
}

// UpdateBalanceByID mocks base method.
func (m *MockIWalletRepo) UpdateBalanceByID(ctx context.Context, walletID int, amount float64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceByID", ctx, walletID, amount)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalanceByID indicates an expected call of UpdateBalanceByID.
func (mr *MockIWalletRepoMockRecorder) UpdateBalanceByID(ctx, walletID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceByID", reflect.TypeOf((*MockIWalletRepo)(nil).UpdateBalanceByID), ctx, walletID, amount)
}

// UpdateStatusWalletLink mocks base method.
func (m *MockIWalletRepo) UpdateStatusWalletLink(ctx context.Context, walletID int, clientSource, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWalletLink", ctx, walletID, clientSource, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusWalletLink indicates an expected call of UpdateStatusWalletLink.
func (mr *MockIWalletRepoMockRecorder) UpdateStatusWalletLink(ctx, walletID, clientSource, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWalletLink", reflect.TypeOf((*MockIWalletRepo)(nil).UpdateStatusWalletLink), ctx, walletID, clientSource, status)
}

// MockIWalletService is a mock of IWalletService interface.
type MockIWalletService struct {
	ctrl     *gomock.Controller
	recorder *MockIWalletServiceMockRecorder
}

// MockIWalletServiceMockRecorder is the mock recorder for MockIWalletService.
type MockIWalletServiceMockRecorder struct {
	mock *MockIWalletService
}

// NewMockIWalletService creates a new mock instance.
func NewMockIWalletService(ctrl *gomock.Controller) *MockIWalletService {
	mock := &MockIWalletService{ctrl: ctrl}
	mock.recorder = &MockIWalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWalletService) EXPECT() *MockIWalletServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIWalletService) Create(ctx context.Context, wallet *models.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIWalletServiceMockRecorder) Create(ctx, wallet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWalletService)(nil).Create), ctx, wallet)
}

// CreateWalletLink mocks base method.
func (m *MockIWalletService) CreateWalletLink(ctx context.Context, clientSource string, req *models.WalletLink) (models.WalletStructOTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWalletLink", ctx, clientSource, req)
	ret0, _ := ret[0].(models.WalletStructOTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWalletLink indicates an expected call of CreateWalletLink.
func (mr *MockIWalletServiceMockRecorder) CreateWalletLink(ctx, clientSource, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWalletLink", reflect.TypeOf((*MockIWalletService)(nil).CreateWalletLink), ctx, clientSource, req)
}

// CreditBalance mocks base method.
func (m *MockIWalletService) CreditBalance(ctx context.Context, userID uint64, req models.TransactionRequest) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreditBalance", ctx, userID, req)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreditBalance indicates an expected call of CreditBalance.
func (mr *MockIWalletServiceMockRecorder) CreditBalance(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreditBalance", reflect.TypeOf((*MockIWalletService)(nil).CreditBalance), ctx, userID, req)
}

// DebitBalance mocks base method.
func (m *MockIWalletService) DebitBalance(ctx context.Context, userID uint64, req models.TransactionRequest) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebitBalance", ctx, userID, req)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DebitBalance indicates an expected call of DebitBalance.
func (mr *MockIWalletServiceMockRecorder) DebitBalance(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebitBalance", reflect.TypeOf((*MockIWalletService)(nil).DebitBalance), ctx, userID, req)
}

// ExGetBalance mocks base method.
func (m *MockIWalletService) ExGetBalance(ctx context.Context, walletID int) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExGetBalance", ctx, walletID)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExGetBalance indicates an expected call of ExGetBalance.
func (mr *MockIWalletServiceMockRecorder) ExGetBalance(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExGetBalance", reflect.TypeOf((*MockIWalletService)(nil).ExGetBalance), ctx, walletID)
}

// ExternalTransaction mocks base method.
func (m *MockIWalletService) ExternalTransaction(ctx context.Context, req models.ExternalTransactionRequest) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalTransaction", ctx, req)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalTransaction indicates an expected call of ExternalTransaction.
func (mr *MockIWalletServiceMockRecorder) ExternalTransaction(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalTransaction", reflect.TypeOf((*MockIWalletService)(nil).ExternalTransaction), ctx, req)
}

// GetBalance mocks base method.
func (m *MockIWalletService) GetBalance(ctx context.Context, userID uint64) (models.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(models.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockIWalletServiceMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockIWalletService)(nil).GetBalance), ctx, userID)
}

// GetWalletHistory mocks base method.
func (m *MockIWalletService) GetWalletHistory(ctx context.Context, userID uint64, param models.WalletHistoryParam) ([]models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletHistory", ctx, userID, param)
	ret0, _ := ret[0].([]models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletHistory indicates an expected call of GetWalletHistory.
func (mr *MockIWalletServiceMockRecorder) GetWalletHistory(ctx, userID, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletHistory", reflect.TypeOf((*MockIWalletService)(nil).GetWalletHistory), ctx, userID, param)
}

// WalletLinkConfirmation mocks base method.
func (m *MockIWalletService) WalletLinkConfirmation(ctx context.Context, walletID int, clientSource, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletLinkConfirmation", ctx, walletID, clientSource, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// WalletLinkConfirmation indicates an expected call of WalletLinkConfirmation.
func (mr *MockIWalletServiceMockRecorder) WalletLinkConfirmation(ctx, walletID, clientSource, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletLinkConfirmation", reflect.TypeOf((*MockIWalletService)(nil).WalletLinkConfirmation), ctx, walletID, clientSource, otp)
}

// WalletUnlink mocks base method.
func (m *MockIWalletService) WalletUnlink(ctx context.Context, walletID int, clientSource string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletUnlink", ctx, walletID, clientSource)
	ret0, _ := ret[0].(error)
	return ret0
}

// WalletUnlink indicates an expected call of WalletUnlink.
func (mr *MockIWalletServiceMockRecorder) WalletUnlink(ctx, walletID, clientSource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletUnlink", reflect.TypeOf((*MockIWalletService)(nil).WalletUnlink), ctx, walletID, clientSource)
}

// MockIWalletAPI is a mock of IWalletAPI interface.
type MockIWalletAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIWalletAPIMockRecorder
}

// MockIWalletAPIMockRecorder is the mock recorder for MockIWalletAPI.
type MockIWalletAPIMockRecorder struct {
	mock *MockIWalletAPI
}

// NewMockIWalletAPI creates a new mock instance.
func NewMockIWalletAPI(ctrl *gomock.Controller) *MockIWalletAPI {
	mock := &MockIWalletAPI{ctrl: ctrl}
	mock.recorder = &MockIWalletAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWalletAPI) EXPECT() *MockIWalletAPIMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIWalletAPI) Create(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", arg0)
}

// Create indicates an expected call of Create.
func (mr *MockIWalletAPIMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWalletAPI)(nil).Create), arg0)
}

// CreateWalletLink mocks base method.
func (m *MockIWalletAPI) CreateWalletLink(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateWalletLink", c)
}

// CreateWalletLink indicates an expected call of CreateWalletLink.
func (mr *MockIWalletAPIMockRecorder) CreateWalletLink(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWalletLink", reflect.TypeOf((*MockIWalletAPI)(nil).CreateWalletLink), c)
}

// CreditBalance mocks base method.
func (m *MockIWalletAPI) CreditBalance(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreditBalance", c)
}

// CreditBalance indicates an expected call of CreditBalance.
func (mr *MockIWalletAPIMockRecorder) CreditBalance(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreditBalance", reflect.TypeOf((*MockIWalletAPI)(nil).CreditBalance), c)
}

// DebitBalance mocks base method.
func (m *MockIWalletAPI) DebitBalance(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DebitBalance", c)
}

// DebitBalance indicates an expected call of DebitBalance.
func (mr *MockIWalletAPIMockRecorder) DebitBalance(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebitBalance", reflect.TypeOf((*MockIWalletAPI)(nil).DebitBalance), c)
}

// ExGetBalance mocks base method.
func (m *MockIWalletAPI) ExGetBalance(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExGetBalance", c)
}

// ExGetBalance indicates an expected call of ExGetBalance.
func (mr *MockIWalletAPIMockRecorder) ExGetBalance(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExGetBalance", reflect.TypeOf((*MockIWalletAPI)(nil).ExGetBalance), c)
}

// ExternalTransaction mocks base method.
func (m *MockIWalletAPI) ExternalTransaction(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExternalTransaction", c)
}

// ExternalTransaction indicates an expected call of ExternalTransaction.
func (mr *MockIWalletAPIMockRecorder) ExternalTransaction(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalTransaction", reflect.TypeOf((*MockIWalletAPI)(nil).ExternalTransaction), c)
}

// GetBalance mocks base method.
func (m *MockIWalletAPI) GetBalance(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetBalance", c)
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockIWalletAPIMockRecorder) GetBalance(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockIWalletAPI)(nil).GetBalance), c)
}

// GetWalletHistory mocks base method.
func (m *MockIWalletAPI) GetWalletHistory(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetWalletHistory", c)
}

// GetWalletHistory indicates an expected call of GetWalletHistory.
func (mr *MockIWalletAPIMockRecorder) GetWalletHistory(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletHistory", reflect.TypeOf((*MockIWalletAPI)(nil).GetWalletHistory), c)
}

// WalletLinkConfirmation mocks base method.
func (m *MockIWalletAPI) WalletLinkConfirmation(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WalletLinkConfirmation", c)
}

// WalletLinkConfirmation indicates an expected call of WalletLinkConfirmation.
func (mr *MockIWalletAPIMockRecorder) WalletLinkConfirmation(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletLinkConfirmation", reflect.TypeOf((*MockIWalletAPI)(nil).WalletLinkConfirmation), c)
}

// WalletUnlink mocks base method.
func (m *MockIWalletAPI) WalletUnlink(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WalletUnlink", c)
}

// WalletUnlink indicates an expected call of WalletUnlink.
func (mr *MockIWalletAPIMockRecorder) WalletUnlink(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletUnlink", reflect.TypeOf((*MockIWalletAPI)(nil).WalletUnlink), c)
}
